### ISSUE TITLE
Applying ufcg to metagenomes

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [steineggerlab/ufcg#1]
Hello, thanks for your tool, this is quite handy!

I am analysing metagenomic datasets and while I do not have bins which can be considered to be MAGs, I would still like to assess broad fungi presence from detection of ufcg directly from the assembly. 
I would like to apply your tool directly to an assembly and assess broad Fungi coverage. 

First question, can ufcg be applied to other things than isolated genomes? If I do gene calling with augustus, it requires a unique organism.
Second question, which of your core/canonical genes can be considered single copy? From your publication, the core seems to be single copy?

**Comment by endixk** [comment]
Hi, thank you for using our tool 😄

As the `profile` module accepts any nucleotide FASTA files regardless of their qualities, you can always try to run the pipeline on MAGs or any sort of roughly assembled contings (i.e. the input need not to be an isolated genome). Just keep in mind that the gene calling sensitivity of the pipeline heavily depends on the assembly quality, therefore some genes might be undetectable by using such input.

All of the 41 core genes can be considered as single copy. Additionally, among 20 canonical genes, RPO21 (RPB1), RPB2, TSR1, TOP1, PAH1, CCT8 and PGK1 can also be regarded as a single copy genes.

**Comment by Sebastien-Raguideau** [comment]
Thanks a lot for the detailed answer :) I am quite happy with false negatives and was worried rather about potential false positive from assumption in Augustus about the type of data analysed. 
That is quite helpful to be able to quantify fungi in metagenomics samples in the same fashion we would do with prokaryotes.
Thansk
