### ISSUE TITLE
Nucleotide alignment with invalid nucleotide "X"

### ISSUE THREAD

**Issue by Changwanseo** [steineggerlab/ufcg#13]
* Environment: UFCG 1.0.3, conda installed version, ubuntu 20.04
* Steps that I've done:
0. Prepare input file
/tmp
       GCA_024703775.1.fna
        .... (many other genome fna files)

1. Call ucg file with "profile"
ufcg profile -i ./tmp 0o ./101_ufcg_profile -t 32 -v --developer --force 1

2. Align with ufcg
ufcg align -i ./101_ufcg_profile -o ./201_ufcg_align_nuc -l acc -a nucleotide -n align -l strain -t 24

* Problems
The resulting alignment includes nucleotide "X", which makes many other programs (such as MAFFT without sequence designation, or geneious) to recognize alignment file as protein alignment. It would be better alignment to change "X" to "N" if "-a nucleotide" flag included

**Comment by endixk** [comment]
Current version has a flawed nucleotide sequence extraction process in which all lowercase bases from the backward strands are converted into the alphabet `X`.

Commit [fe699d1](https://github.com/steineggerlab/ufcg/commit/fe699d19a4ef8c16edece33966f6dbcedcc15361) will not only fix this issue, but also improve the speed of the reverse complement sequence computation in general. I will soon make a new release including this update.
