### ISSUE TITLE
How to resolve warning "Failed to detect environment path" and error "AUGUSTUS-PPX config file is absent or improperly formatted." 

### ISSUE THREAD

**Issue by Changwanseo** [steineggerlab/ufcg#16]
In conda installation, UFCG requires 
`ufcg -t download` to finish installation.

However, current error message 

"Failed to detect environment path. --ppxcfg, --seqpath, and --modelpath options should be specified."
"ERROR! Block profile model directory is incomplete."

is difficult for users to figure out needs of `ufcg -t download`

I suggest to add messages such as these

If this is your first time using UFCG, use "ufcg -t download config
If you haven't downloaded model, use "ufcg -t download minimum" or "ufcg -t download full"

**Comment by endixk** [comment]
Please run `ufcg download -t minimum` if you encounter the following warning and error from `profile` module after the first installation. 

```
Failed to detect environment path. --ppxcfg, --seqpath, and --modelpath options should be specified.
ERROR! AUGUSTUS-PPX config file is absent or improperly formatted.
```

These messages may appear again after updating the conda package into the newest version, even if you've been using the previous version of the pipeline. In such cases, running `ufcg download -t minimum` will resolve the issue as well, however, will occupy unnecessary disk space by downloading another set of databases. 

This will be handled by the next update, along with adding better description to the warning messages.

**Comment by endixk** [comment]
From [release v1.0.5](https://github.com/steineggerlab/ufcg/releases/tag/v1.0.5), the profiling modules will prompt warning and automatically download resources for their initial run.
