### ISSUE TITLE
[Done] Add sensitivity option for `profile` module

### ISSUE THREAD

**Issue by endixk** [steineggerlab/ufcg#19]
Next update will include a new feature for the `profile` module that allows for the customization of profiling sensitivity.

Current algorithm validates the `AUGUSTUS` search result using 3-step fallback search, which uses 80% coverage first, 50% coverage upon failure, and 0% coverage (e-value only) upon failure.

A sensitivity option will be included that can tweak with this algorithm. In detail:
 * `--sensitivity 3` (default): Use original algorithm
 * `--sensitivity 2` : 2-step search (80%, 50%)
 * `--sensitivity 1` : 1-step search (80%)

Lowering sensitivity will significantly reduce the amount of false positive gene calls from the result, however, will become prone to miss some true positive genes as a trade-off. (e.g. failing to call genes with subtle evidences)

**Comment by BrigidaGallone** [comment]
Hi Daniel,

Great to hear and I'm looking forward to testing it. I am actually dealing with a percentage of hits (on average ~8%) wrongly assigned as "Duplicated". Is the copy-level assignment currently based on this 3-step search?

**Comment by endixk** [comment]
Hey Brigida,

Unfortunately adjusting the sensitivity won't affect the number of copies, since it takes next step only if there was no hit found (i.e. lowering sensitivity won't change duplicated calls to singular calls).

Instead, we are also planning to set different coverage thresholds for each gene with empirical values, which *will* improve the copy-level assignment. It will be super helpful if you could share more details around these false duplicate assignments (e.g. which genes or genomes are more susceptible).

**Comment by BrigidaGallone** [comment]
Thanks for your reply and sure, let me put together a proper test case and I will get back to you.
