### ISSUE TITLE
issue with AGUSTUS

### ISSUE THREAD

**Issue by Keevai09** [steineggerlab/ufcg#27]
Hi, I have tried to resolve this issue but failed to do so while using UFCG. Please help asap. 

ERROR! AUGUSTUS-PPX config file is absent or improperly formatted.

I get this in the latest version as well as the old one.

**Comment by endixk** [comment]
Please refer to the comment I wrote before: https://github.com/steineggerlab/ufcg/issues/16#issuecomment-1550556324

If the issue persists, please provide following information for further examination:
- Platform (OS)
- Installation method (manual, conda, etc.)
- Messages when `-dev` option is provided

**Comment by Keevai09** [comment]
Thank you very much for the response. I tried what has been mentioned #16. Now I am facing this issue. 

#First it gives 
Solving dependencies...
UFCG  |:  Failed to solve : augustus
#I provide the path to agustus and I get the below error
ERROR! Invalid binary executable file given 

Please note I have added the agustus path to the bashrc file etc. 

I am using Ubuntu on linux. 
Installed through conda.

**Comment by endixk** [comment]
Hi, sorry for the late reply.

If the installation of `augustus` was successful, running `/path/to/your/augustus --version` from your terminal should print the version number of AUGUSTUS.

Please check if this is the case, and provide the proper and absolute path of `augustus` to the pipeline. If the issue persists, please provide the message with `-dev` option given to your command.

**Comment by Keevai09** [comment]
Sorry for the late response. @endixk . 
Thank you very much for the help. It was an issue with augustus version. I installed augustus 3.5.0. It is working fine now.
